plugins {
    id "io.github.qishr.cascara.meta.java-library" version "0.1.0"
    id "io.github.qishr.cascara.meta.publish" version "0.1.0"
    id("org.gradlex.extra-java-module-info") version "1.13.1"
}


repositories {
	mavenLocal()
	mavenCentral()
}


dependencies {
    implementation(platform("io.github.qishr:cascara-meta-bom:0.1.5"))

    // JUnit
    testImplementation 'org.junit.jupiter:junit-jupiter-api'
    testImplementation 'org.junit.jupiter:junit-jupiter-params'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // Mockito
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.mockito:mockito-junit-jupiter'

    // Cascara
    implementation "io.github.qishr:cascara-common"

    // CSS
    implementation "org.w3c.css:sac:1.3"
}


extraJavaModuleInfo {
    failOnMissingModuleInfo = false
    // failOnAutomaticModules = true

    module("org.w3c.css:sac", "org.w3c.css.sac") {
        exportAllPackages()
    }

}
