version = 0.1.0
java_name = cascara.lang.css
maven_name = cascara-lang-css
group = io.github.qishr
title = Cascara CSS
description = Cascara CSS language processors.
url = https://qishr.github.io/javadoc/cascara.lang.css/
scm_url = https://github.com/qishr/cascara-lang-css
scm_conn = scm:git:https://github.com/qishr/cascara-lang-css.git
scm_dev_conn = scm:git:https://github.com/qishr/cascara-lang-css.git
org.gradle.configuration-cache = false
